# Generated by Django 3.1.2 on 2020-10-25 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('Air Force', 'Air Force'), ('Army', 'Army'), ('Navy', 'Navy'), ('Afcat', 'Afcat'), ('CDS', 'CDS'), ('NDA', 'NDA'), ('NCC', 'NCC')], default='Defence', max_length=10)),
                ('intro', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('published_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
