# Generated by Django 3.1.2 on 2020-10-25 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='published_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
